"pathogen
call pathogen#infect()
call pathogen#helptags()

set nocompatible
set showmode
set autoindent
set cursorline
set ruler
set hidden
set backspace=indent,eol,start
set history=1000
set undofile
set undoreload=10000
set undodir=~/.undo
set autoread
set tags=~/.tags
set complete=.,w,b,u,t,i
set number

set backupskip=/tmp/*,/private/tmp/*"
set nobackup       "no backup files
set nowritebackup  "only in case you don't want a backup file while editing
set noswapfile     "no swap files

let mapleader = ","
syntax on
filetype plugin indent on

au FocusLost * :wa
au VimResized * :wincmd =

au! BufWritePost .vimrc source %

"rainbow parens
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

"tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set nowrap


inoremap jk <esc>
nnoremap / /\v
vnoremap / /\v

"search
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
set gdefault

"minibufexpl
let g:miniBufExplUseSingleClick = 1
let g:miniBufExplMapWindowNavVim = 1

"ctrlp
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/build/*,*/.settings/*,*/bin/*,*/testResults/*,*/webapp/WEB-INF/classes*
let g:ctrlp_max_files = 0
let g:ctrlp_cache_dir = $HOME.'/.cache/ctrlp'
let g:ctrlp_map = '<c-p>'
let g:ctrlp_working_path_mode = 2
let g:ctrlp_user_command = {
    \ 'types': {
      \ 1: ['.git/', 'cd %s && git ls-files'],
      \ 2: ['.hg/', 'hg --cwd %s locate -I .'],
      \ },
    \ 'fallback': 'find %s -type f'
    \ }
let g:ctrlp_lazy_update = 1

"nerdtree
noremap <leader>n :NERDTreeFind<cr>
noremap <leader>m :NERDTreeToggle<cr>

"java    
let java_highlight_all=1
let java_highlight_functions="style"
let java_allow_cpp_keywords=1

"gvim
if has('gui_running')
  set guioptions-=T  " no toolbar
endif
